language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    # Update Android SDK Tools
    - tools
    - build-tools-25.0.0
    - android-23
    # Support library
    - extra-android-support
    - extra-android-m2repositor
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - '$HOME/.sonar/cache'
 
before_script: 
  - chmod +x gradlew
script: 
  - chmod +x gradlew
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)


notifications:
  email: false
after_success:
	- java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  #- bash <(curl -s https://codecov.io/bash)
